services:
  event-bot:
    build: .
    container_name: discord_event_bot
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Europe/Rome
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro